apiVersion : apps/v1
kind: Deployment
metadata:
  name: "myakscluster-66b0"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "myakscluster-66b0"
  template:
    metadata:
      labels:
        app: "myakscluster-66b0"
    spec:
      containers:
        - name: "myakscluster-66b0"
          image: "myacr9999.azurecr.io/myakscluster"
          ports:
          - containerPort: 8080