apiVersion: v1
kind: Service
metadata:
    name: "myadks-be9f"
    labels:
        app: "myadks-be9f"
spec:
    type: LoadBalancer
    ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
    selector:
        app: "myadks-be9f"