on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n myaksacr2022 -g myaksacr20228703-rg --location "East US" --sku Standard --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n myaksacr2022 --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n myaksacr2022 --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n myaksacr2022 --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: myaksacr2022.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t myaksacr2022.azurecr.io/myaks:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push myaksacr2022.azurecr.io/myaks:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_myaks_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep myaksb9d3-pythonapp | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace myaksb9d3-pythonapp`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: myaksb9d3-pythonapp
        container-registry-url: myaksacr2022.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: myaksdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: myaksb9d3-pythonapp
        manifests: |
          manifests/deployment-6.yml
          manifests/service-6.yml
        images: |
          myaksacr2022.azurecr.io/myaks:${{ github.sha }}
        imagepullsecrets: |
          myaksdockerauth   
