on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n myacr2025 -g myacr202583fb-rg --location "East US" --sku Standard --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n myacr2025 --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n myacr2025 --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n myacr2025 --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: myacr2025.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t myacr2025.azurecr.io/myask:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push myacr2025.azurecr.io/myask:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_myask_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep myaskb38a-python-app | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace myaskb38a-python-app`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: myaskb38a-python-app
        container-registry-url: myacr2025.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: myaskdockerauth
       
    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: myaskb38a-python-app
        manifests: |
          manifests/deployment-9.yml
          manifests/service-9.yml
        images: |
          myacr2025.azurecr.io/myask:${{ github.sha }}
        imagepullsecrets: |
          myaskdockerauth   
